### ISSUE TITLE
Fails with empty line within function definition

### ISSUE THREAD

**Issue by mcuntz** [jameskermode/f90wrap#105]
Dear James,

f90wrap has a problem if there is one or more empty lines within the function definition. The test code is:

    module itestit

      implicit none

      private
      
      public :: testit1
      public :: testit2
      
    contains

      subroutine testit1( &
           x &
           )

        implicit none

        real, dimension(:), intent(inout) :: x

        x = 1.*x

      end subroutine testit1

      subroutine testit2( &
           x &

           )

        implicit none

        real, dimension(:), intent(inout) :: x

        x = 2.*x

      end subroutine testit2

    end module itestit

The subroutine testit1 works well, while parser.py fails with subroutine testit2:

    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.7/bin/f90wrap", line 298, in main
        parse_tree = fparse.read_files(args.files, doc_plugin_filename=doc_plugin_fname)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/f90wrap/parser.py", line 1382, in read_files
        check = check_module(cline, file)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/f90wrap/parser.py", line 551, in check_module
        check = check_subt(cl, file)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/f90wrap/parser.py", line 645, in check_subt
        del (argl[len(argl) - 1])
    IndexError: list assignment index out of range
    f90wrap: IndexError('list assignment index out of range')
             for help use --help

The empty lines come from the fact that I have optional allocatable output that I remove with preprocessor flags when using the parser but leave them for the pure Fortran code.

Kind regards
Matthias

**Comment by mcuntz** [comment]
Hey James,

Couldn't you just delete empty lines or lines with only whitespace before launching the rest of the parser? Would at least solve this problem. Cannot of think of any other side effects.

Kind regards
Matthias
