### ISSUE TITLE
ValueError with Nix environments

### ISSUE THREAD

**Issue by HaoZeke** [jameskermode/f90wrap#124]
Hi!
While using `f2py-f90wrap` I am running into the following error:
```
build_src: building npy-pkg config files                                                                                      [72/26330]
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu',
 'g95', 'pathf95', 'nagfor']'
customize Gnu95FCompiler
Found executable /users/home/rog32/.nix-profile/bin/gfortran
Found executable /users/home/rog32/.nix-profile/bin/ld
Found executable /users/home/rog32/.nix/store/l06x1g82byww0dyrgkl46wgnw3b5s8sc-binutils-2.31.1/bin/ar
Found executable /users/home/rog32/.nix/store/l06x1g82byww0dyrgkl46wgnw3b5s8sc-binutils-2.31.1/bin/ranlib
analyzevars: charselector={'len': '1'} unhandled.analyzevars: charselector={'len': '*'} unhandled.analyzevars: charselector={'len': '1'}
 unhandled.analyzevars: charselector={'len': '*'} unhandled.analyzevars: charselector={'len': '*'} unhandled.analyzevars: charselector={
'len': '*'} unhandled.analyzevars: charselector={'len': '*'} unhandled.analyzevars: charselector={'len': '*'} unhandled.analyzevars: cha
rselector={'len': '*'} unhandled.analyzevars: charselector={'len': '*'} unhandled.analyzevars: charselector={'len': '1'} unhandled.analy
zevars: charselector={'len': '1'} unhandled.analyzevars: charselector={'len': '1'} unhandled.analyzevars: charselector={'len': '*'} unha
ndled.analyzevars: charselector={'len': '*'} unhandled.analyzevars: charselector={'len': '10240'} unhandled.analyzevars: charselector={'
len': '*'} unhandled.analyzevars: charselector={'len': '*'} unhandled.analyzevars: charselector={'len': '1'} unhandled.analyzevars: char
selector={'len': '*'} unhandled.analyzevars: charselector={'len': '1'} unhandled.analyzevars: charselector={'len': '*'} unhandled.analyz
evars: charselector={'len': '1'} unhandled.analyzevars: charselector={'len': '1'} unhandled.analyzevars: charselector={'len': '1'} unhan
dled.analyzevars: charselector={'len': '1'} unhandled.analyzevars: charselector={'len': '1'} unhandled.Traceback (most recent call last)
:
  File "/users/home/rog32/.nix/store/nwxjryb072sjm595smi508s03sf204fy-python3.8-f90wrap-0.2.3/bin/.f2py-f90wrap-wrapped", line 183, in <
module>
    numpy.f2py.main()
  File "/users/home/rog32/.nix/store/1smgyj7rppdmfx6jz9b1a7smmvdgkd7l-python3-3.8.5-env/lib/python3.8/site-packages/numpy/f2py/f2py2e.py
", line 692, in main
    run_compile()
  File "/users/home/rog32/.nix/store/1smgyj7rppdmfx6jz9b1a7smmvdgkd7l-python3-3.8.5-env/lib/python3.8/site-packages/numpy/f2py/f2py2e.py
", line 659, in run_compile
    setup(ext_modules=[ext])
  File "/users/home/rog32/.nix/store/1smgyj7rppdmfx6jz9b1a7smmvdgkd7l-python3-3.8.5-env/lib/python3.8/site-packages/numpy/distutils/core
.py", line 169, in setup
    return old_setup(**new_attr)
  File "/users/home/rog32/.nix/store/ky989br2f0mhpg30zkys3rjizsxyfimk-python3-3.8.5/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
 File "/users/home/rog32/.nix/store/ky989br2f0mhpg30zkys3rjizsxyfimk-python3-3.8.5/lib/python3.8/distutils/dist.py", line 966, in run_c
ommands
    self.run_command(cmd)
  File "/users/home/rog32/.nix/store/ky989br2f0mhpg30zkys3rjizsxyfimk-python3-3.8.5/lib/python3.8/distutils/dist.py", line 985, in run_c
ommand
    cmd_obj.run()
  File "/users/home/rog32/.nix/store/1smgyj7rppdmfx6jz9b1a7smmvdgkd7l-python3-3.8.5-env/lib/python3.8/site-packages/numpy/distutils/comm
and/build.py", line 40, in run
    old_build.run(self)
  File "/users/home/rog32/.nix/store/ky989br2f0mhpg30zkys3rjizsxyfimk-python3-3.8.5/lib/python3.8/distutils/command/build.py", line 135,
 in run
    self.run_command(cmd_name)
  File "/users/home/rog32/.nix/store/ky989br2f0mhpg30zkys3rjizsxyfimk-python3-3.8.5/lib/python3.8/distutils/cmd.py", line 313, in run_co
mmand
    self.distribution.run_command(command)
  File "/users/home/rog32/.nix/store/ky989br2f0mhpg30zkys3rjizsxyfimk-python3-3.8.5/lib/python3.8/distutils/dist.py", line 985, in run_c
ommand
    cmd_obj.run()
  File "/users/home/rog32/.nix/store/1smgyj7rppdmfx6jz9b1a7smmvdgkd7l-python3-3.8.5-env/lib/python3.8/site-packages/numpy/distutils/comm
and/build_ext.py", line 228, in run
    self._f77_compiler = new_fcompiler(compiler=self.fcompiler,
  File "/users/home/rog32/.nix/store/1smgyj7rppdmfx6jz9b1a7smmvdgkd7l-python3-3.8.5-env/lib/python3.8/site-packages/numpy/distutils/fcom
piler/__init__.py", line 880, in new_fcompiler
    compiler = get_default_fcompiler(plat, requiref90=requiref90,
  File "/users/home/rog32/.nix/store/1smgyj7rppdmfx6jz9b1a7smmvdgkd7l-python3-3.8.5-env/lib/python3.8/site-packages/numpy/distutils/fcom
piler/__init__.py", line 851, in get_default_fcompiler
    compiler_type =  _find_existing_fcompiler(matching_compiler_types,
  File "/users/home/rog32/.nix/store/1smgyj7rppdmfx6jz9b1a7smmvdgkd7l-python3-3.8.5-env/lib/python3.8/site-packages/numpy/distutils/fcom
piler/__init__.py", line 802, in _find_existing_fcompiler
    c.customize(dist)
  File "/users/home/rog32/.nix/store/1smgyj7rppdmfx6jz9b1a7smmvdgkd7l-python3-3.8.5-env/lib/python3.8/site-packages/numpy/distutils/fcom
piler/__init__.py", line 507, in customize
    get_flags('opt', oflags)
  File "/users/home/rog32/.nix/store/1smgyj7rppdmfx6jz9b1a7smmvdgkd7l-python3-3.8.5-env/lib/python3.8/site-packages/numpy/distutils/fcom
piler/__init__.py", line 498, in get_flags
    flags.extend(getattr(self.flag_vars, tag))
  File "/users/home/rog32/.nix/store/1smgyj7rppdmfx6jz9b1a7smmvdgkd7l-python3-3.8.5-env/lib/python3.8/site-packages/numpy/distutils/fcom
piler/environment.py", line 37, in __getattr__
    return self._get_var(name, conf_desc)
  File "/users/home/rog32/.nix/store/1smgyj7rppdmfx6jz9b1a7smmvdgkd7l-python3-3.8.5-env/lib/python3.8/site-packages/numpy/distutils/fcom
piler/environment.py", line 53, in _get_var
    var = self._hook_handler(name, hook)
  File "/users/home/rog32/.nix/store/1smgyj7rppdmfx6jz9b1a7smmvdgkd7l-python3-3.8.5-env/lib/python3.8/site-packages/numpy/distutils/fcom
piler/__init__.py", line 705, in _environment_hook
    return hook()
  File "/users/home/rog32/.nix/store/1smgyj7rppdmfx6jz9b1a7smmvdgkd7l-python3-3.8.5-env/lib/python3.8/site-packages/numpy/distutils/fcom
piler/gnu.py", line 229, in get_flags_opt
    v = self.get_version()
  File "/users/home/rog32/.nix/store/1smgyj7rppdmfx6jz9b1a7smmvdgkd7l-python3-3.8.5-env/lib/python3.8/site-packages/numpy/distutils/fcom
piler/__init__.py", line 426, in get_version
    version = CCompiler.get_version(self, force=force, ok_status=ok_status)
  File "/users/home/rog32/.nix/store/1smgyj7rppdmfx6jz9b1a7smmvdgkd7l-python3-3.8.5-env/lib/python3.8/site-packages/numpy/distutils/ccom
piler.py", line 90, in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
  File "/users/home/rog32/.nix/store/1smgyj7rppdmfx6jz9b1a7smmvdgkd7l-python3-3.8.5-env/lib/python3.8/site-packages/numpy/distutils/ccom
piler.py", line 657, in CCompiler_get_version
    version = matcher(output)
  File "/users/home/rog32/.nix/store/1smgyj7rppdmfx6jz9b1a7smmvdgkd7l-python3-3.8.5-env/lib/python3.8/site-packages/numpy/distutils/fcom
piler/gnu.py", line 278, in version_match
    v = self.gnu_version_match(version_string)
  File "/users/home/rog32/.nix/store/1smgyj7rppdmfx6jz9b1a7smmvdgkd7l-python3-3.8.5-env/lib/python3.8/site-packages/numpy/distutils/fcom
piler/gnu.py", line 80, in gnu_version_match
    raise ValueError(err + version_string)
ValueError: A valid Fortran version was not found in this string:
/users/home/rog32/.nix/store/jjpqh1z7iqzyrqy6zx3bnrxi87ygf4fh-bash-4.4-p23/bin/bash: warning: setlocale: LC_ALL: cannot change locale (e
n_US.UTF-8)
9.3.0
```

Any suggestions would be very welcome.

**Comment by HaoZeke** [comment]
My mistake, was foiled by a hardcoded path in a massive shell file.
