### ISSUE TITLE
crash in pywrapgen.py

### ISSUE THREAD

**Issue by yvesch** [jameskermode/f90wrap#16]
Hello,

I have a problem running f90wrap on both examples included in the package. As documented, I tried to run `make` for the examples, but the test fail with an error inside `pywrapgen.py`:
<pre>
  File "/bira-iasb/home/yvesc/test/languages/python/f90wrap_test/lib/python2.6/site-packages/f90wrap/pywrapgen.py", line 468, in write_repr                                                                                                     
    self.write(r"ret = ['<{}>".format(node.name) + r"{\n']")                                                            
ValueError: zero length field name in format                                                                            
</pre>

I reverted to a version before the [commit of May 9, 2015 by rpfische] (https://github.com/jameskermode/f90wrap/commit/7c8f03e9aaa84b4211a83da4c12f8f47d7e6213e), and could build the examples; the `example2` ran successfully, but there is still another issue with `mockderivetype` example that I try to understand now.

FYI, here is the full log of make:

<pre>
(f90wrap_test3)yvesc@tethys->tethys:/home/yvesc/test/languages/python/f90wrap_install/f90wrap/examples/mockderivetype> make                                                                                                                     
gfortran -x f95-cpp-input -fPIC -c leveltwomod.f90 -o leveltwomod.o                                                     
gfortran -x f95-cpp-input -fPIC -c define.f90 -o define.o                                                               
gfortran -x f95-cpp-input -fPIC -c fwrap.f90 -o fwrap.o                                                                 
ar src libsrc.a leveltwomod.o define.o fwrap.o                                                                          
gfortran -E -x f95-cpp-input -fPIC leveltwomod.f90  -o leveltwomod.fpp                                                  
gfortran -E -x f95-cpp-input -fPIC define.f90  -o define.fpp                                                            
gfortran -E -x f95-cpp-input -fPIC fwrap.f90  -o fwrap.fpp                                                              
f90wrap -m mockdt leveltwomod.fpp define.fpp fwrap.fpp -k kind_map -v                                                   
Kind map read from file "'kind_map'" : (also saved to .f2py_f2cmap)                                                     
{'complex': {'': 'complex_float',                                                                                       
             '8': 'complex_double',                                                                                     
             'dp': 'complex_double'},                                                                                   
 'integer': {'': 'int', '8': 'long_long', 'dp': 'long_long'},                                                           
 'real': {'': 'float', '8': 'double', 'dp': 'double'}}                                                                  

Constructors:
('initialise_ptr', 'initialise', 'allocate')

Destructors:
('finalise', 'deallocate')

Short names for derived types read from file "None"
{}                                                 

String lengths read from file "None":
{}                                   

Initialisation lines for derived types read from file "None":
{}                                                           

Argument name map:
{}                

Size of Fortran derived type pointers is 2 bytes.

Parsing Fortran source files ['leveltwomod.fpp', 'define.fpp', 'fwrap.fpp'] ...
DEBUG:root:processing file leveltwomod.fpp                                     
INFO:root:parser reading type leveltwo                                         
DEBUG:root:    type leveltwo                                                   
DEBUG:root:  module leveltwomod                                                
DEBUG:root:processing file define.fpp                                          
INFO:root:parser reading type atype                                            
DEBUG:root:    type atype                                                      
INFO:root:parser reading type unused_type                                      
DEBUG:root:    type unused_type                                                
DEBUG:root:    module subroutine use_set_vars                                  
DEBUG:root:    module function return_a_type_func                              
DEBUG:root:    module subroutine return_a_type_sub                             
DEBUG:root:  module define_a_type                                              
DEBUG:root:  subroutine top_level                                              
INFO:root:parser reading type horrible_type                                    
DEBUG:root:    type horrible_type                                              
DEBUG:root:  module horrible                                                   
DEBUG:root:processing file fwrap.fpp                                           
DEBUG:root:    module subroutine do_stuff                                      
DEBUG:root:    module subroutine not_used                                      
DEBUG:root:  module use_a_type                                                 
done parsing source.                                                           

DEBUG:root:type leveltwo defined in module leveltwomod
DEBUG:root:type atype defined in module define_a_type 
DEBUG:root:type unused_type defined in module define_a_type
DEBUG:root:type horrible_type defined in module horrible   
Derived types detected in Fortran source files:            
{'atype': Type(name=atype),                                
 'horrible_type': Type(name=horrible_type),                
 'leveltwo': Type(name=leveltwo),                          
 'type(atype)': Type(name=atype),                          
 'type(horrible_type)': Type(name=horrible_type),          
 'type(leveltwo)': Type(name=leveltwo),                    
 'type(unused_type)': Type(name=unused_type),              
 'unused_type': Type(name=unused_type)}                    

DEBUG:root:marking public symbol leveltwo
DEBUG:root:marking public symbol rl      
DEBUG:root:marking public symbol atype   
DEBUG:root:marking public symbol bool    
DEBUG:root:marking public symbol integ   
DEBUG:root:marking public symbol rl      
DEBUG:root:marking public symbol vec     
DEBUG:root:marking public symbol dtype   
DEBUG:root:marking public symbol unused_type
DEBUG:root:marking public symbol a_set_real 
DEBUG:root:marking public symbol a_set_bool 
DEBUG:root:marking public symbol use_set_vars
DEBUG:root:marking public symbol return_a_type_func
DEBUG:root:marking public symbol return_a_type_sub 
DEBUG:root:marking public symbol horrible_type     
DEBUG:root:marking public symbol x                 
DEBUG:root:marking public symbol a_real            
DEBUG:root:marking public symbol p                 
DEBUG:root:marking public symbol p_array           
DEBUG:root:marking public symbol vector            
DEBUG:root:marking public symbol do_stuff          
DEBUG:root:marking public symbol not_used          
DEBUG:root:visiting Module(name=leveltwomod)       
DEBUG:root:visiting Type(name=leveltwo)            
DEBUG:root:visiting Module(name=define_a_type)     
DEBUG:root:visiting Type(name=atype)               
DEBUG:root:visiting Type(name=unused_type)         
DEBUG:root:visiting Module(name=horrible)          
DEBUG:root:visiting Type(name=horrible_type)       
DEBUG:root:visiting Module(name=use_a_type)        
INFO:root:adding missing constructor for leveltwo  
INFO:root:adding missing constructor for atype     
INFO:root:adding missing constructor for unused_type
INFO:root:adding missing constructor for horrible_type
INFO:root:adding missing destructor for leveltwo      
INFO:root:adding missing destructor for atype         
INFO:root:adding missing destructor for unused_type   
INFO:root:adding missing destructor for horrible_type 
Reading .f2py_f2cmap ...                              
        Warning: redefinition of {'real':{'':'float'->'float'}}
        Mapping "real(kind=)" to "float"                       
        Warning: redefinition of {'real':{'8':'double'->'double'}}
        Mapping "real(kind=8)" to "double"                        
        Mapping "real(kind=dp)" to "double"                       
        Warning: redefinition of {'integer':{'':'int'->'int'}}    
        Mapping "integer(kind=)" to "int"                         
        Warning: redefinition of {'integer':{'8':'long_long'->'long_long'}}
        Mapping "integer(kind=8)" to "long_long"                           
        Mapping "integer(kind=dp)" to "long_long"                          
        Warning: redefinition of {'complex':{'':'complex_float'->'complex_float'}}
        Mapping "complex(kind=)" to "complex_float"                               
        Warning: redefinition of {'complex':{'8':'complex_float'->'complex_double'}}
        Mapping "complex(kind=8)" to "complex_double"                               
        Mapping "complex(kind=dp)" to "complex_double"                              
Succesfully applied user defined changes from .f2py_f2cmap                          
DEBUG:root:allocating arg "ret_a" in return_a_type_func                             
DEBUG:root:allocating arg "this" in leveltwo_initialise                             
DEBUG:root:deallocating arg "this" in leveltwo_finalise                             
DEBUG:root:allocating arg "this" in atype_initialise                                
DEBUG:root:deallocating arg "this" in atype_finalise                                
DEBUG:root:allocating arg "this" in unused_type_initialise                          
DEBUG:root:deallocating arg "this" in unused_type_finalise                          
DEBUG:root:allocating arg "this" in horrible_type_initialise                        
DEBUG:root:deallocating arg "this" in horrible_type_finalise                        
INFO:root:PythonWrapperGenerator visiting module leveltwomod                        
INFO:root:PythonWrapperGenerator visiting type leveltwo                             
INFO:root:PythonWrapperGenerator visiting routine leveltwo_initialise               
INFO:root:PythonWrapperGenerator visiting routine leveltwo_finalise                 
Traceback (most recent call last):                                                  
  File "/home/yvesc/test/languages/python/f90wrap_test3/bin/f90wrap", line 244, in main
    init_file=args.init_file).visit(py_tree)                                           
  File "/bira-iasb/home/yvesc/test/languages/python/f90wrap_test/lib/python2.6/site-packages/f90wrap/fortran.py", line 445, in visit                                                                                                            
    result = visitor(node)                                                                                              
  File "/bira-iasb/home/yvesc/test/languages/python/f90wrap_test/lib/python2.6/site-packages/f90wrap/pywrapgen.py", line 168, in visit_Root                                                                                                     
    self.generic_visit(node)                                                                                            
  File "/bira-iasb/home/yvesc/test/languages/python/f90wrap_test/lib/python2.6/site-packages/f90wrap/fortran.py", line 453, in generic_visit                                                                                                    
    self.visit(item)                                                                                                    
  File "/bira-iasb/home/yvesc/test/languages/python/f90wrap_test/lib/python2.6/site-packages/f90wrap/fortran.py", line 445, in visit                                                                                                            
    result = visitor(node)                                                                                              
  File "/bira-iasb/home/yvesc/test/languages/python/f90wrap_test/lib/python2.6/site-packages/f90wrap/pywrapgen.py", line 204, in visit_Module                                                                                                   
    self.generic_visit(node)                                                                                            
  File "/bira-iasb/home/yvesc/test/languages/python/f90wrap_test/lib/python2.6/site-packages/f90wrap/fortran.py", line 453, in generic_visit                                                                                                    
    self.visit(item)                                                                                                    
  File "/bira-iasb/home/yvesc/test/languages/python/f90wrap_test/lib/python2.6/site-packages/f90wrap/fortran.py", line 445, in visit                                                                                                            
    result = visitor(node)                                                                                              
  File "/bira-iasb/home/yvesc/test/languages/python/f90wrap_test/lib/python2.6/site-packages/f90wrap/pywrapgen.py", line 407, in visit_Type                                                                                                     
    self.write_repr(node, properties)                                                                                   
  File "/bira-iasb/home/yvesc/test/languages/python/f90wrap_test/lib/python2.6/site-packages/f90wrap/pywrapgen.py", line 468, in write_repr                                                                                                     
    self.write(r"ret = ['<{}>".format(node.name) + r"{\n']")                                                            
ValueError: zero length field name in format                                                                            
f90wrap: ValueError('zero length field name in format',)                                                                
         for help use --help                                                                                            
Traceback (most recent call last):                                                                                      
  File "/home/yvesc/test/languages/python/f90wrap_test3/bin/f90wrap", line 264, in <module>                             
    sys.exit(main())                                                                                                    
  File "/home/yvesc/test/languages/python/f90wrap_test3/bin/f90wrap", line 244, in main                                 
    init_file=args.init_file).visit(py_tree)                                                                            
  File "/bira-iasb/home/yvesc/test/languages/python/f90wrap_test/lib/python2.6/site-packages/f90wrap/fortran.py", line 445, in visit                                                                                                            
    result = visitor(node)                                                                                              
  File "/bira-iasb/home/yvesc/test/languages/python/f90wrap_test/lib/python2.6/site-packages/f90wrap/pywrapgen.py", line 168, in visit_Root                                                                                                     
    self.generic_visit(node)                                                                                            
  File "/bira-iasb/home/yvesc/test/languages/python/f90wrap_test/lib/python2.6/site-packages/f90wrap/fortran.py", line 453, in generic_visit                                                                                                    
    self.visit(item)                                                                                                    
  File "/bira-iasb/home/yvesc/test/languages/python/f90wrap_test/lib/python2.6/site-packages/f90wrap/fortran.py", line 445, in visit                                                                                                            
    result = visitor(node)                                                                                              
  File "/bira-iasb/home/yvesc/test/languages/python/f90wrap_test/lib/python2.6/site-packages/f90wrap/pywrapgen.py", line 204, in visit_Module                                                                                                   
    self.generic_visit(node)                                                                                            
  File "/bira-iasb/home/yvesc/test/languages/python/f90wrap_test/lib/python2.6/site-packages/f90wrap/fortran.py", line 453, in generic_visit                                                                                                    
    self.visit(item)                                                                                                    
  File "/bira-iasb/home/yvesc/test/languages/python/f90wrap_test/lib/python2.6/site-packages/f90wrap/fortran.py", line 445, in visit                                                                                                            
    result = visitor(node)                                                                                              
  File "/bira-iasb/home/yvesc/test/languages/python/f90wrap_test/lib/python2.6/site-packages/f90wrap/pywrapgen.py", line 407, in visit_Type                                                                                                     
    self.write_repr(node, properties)                                                                                   
  File "/bira-iasb/home/yvesc/test/languages/python/f90wrap_test/lib/python2.6/site-packages/f90wrap/pywrapgen.py", line 468, in write_repr                                                                                                     
    self.write(r"ret = ['<{}>".format(node.name) + r"{\n']")                                                            
ValueError: zero length field name in format                                                                            
make: *** [_mockdt.so] Error 1                                                                                          
</pre>

**Comment by jameskermode** [comment]
Both of these errors look like Python 2.6 compatibility problems, I'll check in a fix. I'll try to add some unit tests to catch this in future.

**Comment by jameskermode** [comment]
Does [this commit] (https://github.com/jameskermode/f90wrap/commit/06305002f7b45848e6935fad1719292fb83007f9) fix your problem?

**Comment by yvesch** [comment]
Dear James,

Thanks! that solves the problem in `pywrapgen.py`, indeed.
The second problem I have in the `mockderivetype` example seems related to the way intent(out) arguments are handled by the wrapper; I'll try to figure out what happens and open a separate issue for that.

Once again, many thanks for the good job!
