### ISSUE TITLE
TypeError when passing only one of `--constructors` and `--destructors`

### ISSUE THREAD

**Issue by Rykath** [jameskermode/f90wrap#234]
When passing only one of the two options `--constructors` and `--destructors`, e.g. 
```bash
f90wrap mytype.f90 --destructors mytype_free
```
f90wrap (v0.2.15) will throw the error:
```
f90wrap: TypeError('can only concatenate tuple (not "list") to tuple')
```

<details><summary> Traceback </summary>

```
Traceback (most recent call last):
  File ".../lib/python3.10/site-packages/f90wrap/scripts/main.py", line 352, in main
    tree = tf.transform_to_generic_wrapper(tree,
  File ".../lib/python3.10/site-packages/f90wrap/transform.py", line 1266, in transform_to_generic_wrapper
    destructors, remove_optional_arguments).visit(tree)
  File ".../lib/python3.10/site-packages/f90wrap/fortran.py", line 504, in visit
    result = visitor(node)
  File ".../lib/python3.10/site-packages/f90wrap/fortran.py", line 533, in generic_visit
    value = self.visit(value)
  File ".../lib/python3.10/site-packages/f90wrap/fortran.py", line 504, in visit
    result = visitor(node)
  File ".../lib/python3.10/site-packages/f90wrap/transform.py", line 399, in visit_Module
    return self.generic_visit(node)
  File ".../lib/python3.10/site-packages/f90wrap/fortran.py", line 533, in generic_visit
    value = self.visit(value)
  File ".../lib/python3.10/site-packages/f90wrap/fortran.py", line 504, in visit
    result = visitor(node)
  File ".../lib/python3.10/site-packages/f90wrap/transform.py", line 360, in visit_Type
    return self.generic_visit(node)
  File ".../lib/python3.10/site-packages/f90wrap/fortran.py", line 533, in generic_visit
    value = self.visit(value)
  File ".../lib/python3.10/site-packages/f90wrap/fortran.py", line 504, in visit
    result = visitor(node)
  File ".../lib/python3.10/site-packages/f90wrap/transform.py", line 212, in visit_Binding
    new_proc = self.visit_Procedure(proc)
  File ".../lib/python3.10/site-packages/f90wrap/transform.py", line 224, in visit_Procedure
    for suff in self.constructors + self.destructors:
TypeError: can only concatenate tuple (not "list") to tuple
```
</details>

## Workaround

Passing an empty option for the other argument, e.g. 
```bash
f90wrap mytype.f90 --constructors --destructors mytype_free
```
causes no error. (This seems to be purely an error with how the arguments are parsed.)

**Comment by jameskermode** [comment]
Thanks for reporting, I agree this looks like an argument parsing bug only. A PR to fix it would be very welcome!

**Comment by jameskermode** [comment]
Closed by #251. Reopen if there's still a problem.
